spring:
  application:
    name: HHH_BE
  data:
    mongodb:
      uri: ${MONGO_URI}

  mail:
    host: smtp.gmail.com
    port: 587
    username: haspring@dsm.hs.kr
    password: nefhzscunhjqgyga
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


server:
  port: 7311
