spring:
  application:
    name: HHH_BE
  data:
    mongodb:
      uri: ${MONGO_URI}
      auto-index-creation: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: haspring@dsm.hs.kr
    password: ${PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 7311
